version: '3.8'

services:
  your-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=your_very_strong_secret
      - DB_PATH=/data/prod.db
    volumes:
      - appdata:/data

volumes:
  appdata: